// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSSViewer.LocalDb;

namespace RSSViewer.Migrations.LocalDb
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20210515084104_AddStateChangeReason")]
    partial class AddStateChangeReason
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RSSViewer.LocalDb.RssItem", b =>
                {
                    b.Property<string>("FeedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RssId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("MagnetLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StateChangeReason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateChangeReasonExtras")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("FeedId", "RssId");

                    b.ToTable("RssItems");
                });

            modelBuilder.Entity("RSSViewer.LocalDb.SyncSourceInfo", b =>
                {
                    b.Property<string>("SyncSourceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSyncId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SyncSourceId");

                    b.ToTable("SyncSourceInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
