// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSSViewer.HttpCacheDb;

namespace RSSViewer.Migrations.HttpCacheDb
{
    [DbContext(typeof(HttpCacheDbContext))]
    [Migration("20210123153913_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RSSViewer.HttpCacheDb.CachedRequest", b =>
                {
                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ResponseBody")
                        .HasColumnType("BLOB");

                    b.HasKey("Uri");

                    b.ToTable("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
