// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSSViewer.RulesDb;

namespace RSSViewer.Migrations
{
    [DbContext(typeof(RulesDbContext))]
    [Migration("20210414061306_AddTag")]
    partial class AddTag
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RSSViewer.RulesDb.MatchRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Argument")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("AutoDisabledAfterLastMatched")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("AutoExpiredAfterLastMatched")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HandlerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HandlerType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreCase")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastMatched")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OnFeedId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMatchedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MatchRules");
                });

            modelBuilder.Entity("RSSViewer.RulesDb.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagGroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("RSSViewer.RulesDb.MatchRule", b =>
                {
                    b.HasOne("RSSViewer.RulesDb.MatchRule", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
